name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKIP_DB_INIT: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          source-url: https://nuget.pkg.github.com/mihainegrisan/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List NuGet sources
        run: dotnet nuget list source

      - name: Restore dependencies
        run: dotnet restore MFO.UserService.sln

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Debug - List files
        run: find src/MFO.UserService.Clients -type f

      - name: What files exist in MFO.UserService.Clients
        run: ls -la src/MFO.UserService.Clients/

      - name: Build
        run: dotnet build MFO.UserService.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test MFO.UserService.sln --no-build --configuration Release --verbosity normal